apiVersion: v2
name: laravel
description: Laravel helm chart
version: 1.2.0
dependencies:
- name: generic
  version: 1.2.0
  repository: https://charts.kool.dev
- name: mysql
  condition: mysql.enabled
  version: 1.2.0
  repository: https://charts.kool.dev
- name: redis
  condition: redis.enabled
  version: 1.2.0
  repository: https://charts.kool.dev
