apiVersion: v2
name: wordpress
description: Wordpress helm chart
version: 1.1.0
dependencies:
- name: generic
  version: 1.1.0
  repository: https://charts.kool.dev
- name: mysql
  condition: mysql.enabled
  version: 1.1.0
  repository: https://charts.kool.dev
- name: redis
  condition: redis.enabled
  version: 1.1.0
  repository: https://charts.kool.dev
