dind:
  generic:
    # strategy:
    #   type: Recreate
    serviceAccount:
      create: false

generic:
  nameOverride: kool

  containers:
    kool:
      image:
        repository: kooldev/kool
        pullPolicy: Always
        tag: 1.0
      env:
        - name: "DOCKER_HOST"
          value: "tcp://localhost:2375"
      # volumeMounts:
      #   - name: bins
      #     mountPath: "/kool"

    # configMaps:
    #   - name: bins
    #     files:
    #       bash_1: |
    #         ...
    #       bash_2: |
    #         ...

    # volumes:
    #   - name: bins
    #     configMap:
    #       name: bins
    #       defaultMode: 0755
