{{- if and (.Values.serviceAccount.create) (.Values.serviceAccount.role.create) -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{ include "generic.serviceAccountName" . }}
rules: {{ .Values.serviceAccount.role.rules | nindent 2 }}
{{- end }}
