{{- if and (.Values.serviceAccount.create) (.Values.serviceAccount.role.create) -}}
{{- $serviceAccountName := include "generic.serviceAccountName" . -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $serviceAccountName }}
subjects:
  - kind: ServiceAccount
    name: {{ $serviceAccountName }}
    namespace: {{ .Release.Namespace }}
roleRef:
   kind: Role
   name: {{ $serviceAccountName }}
   apiGroup: rbac.authorization.k8s.io
{{- end }}
