{{- if .Values.secrets }}
{{- $fullName := include "generic.fullname" . -}}
{{- $labels := include "generic.labels" . -}}
{{- range $secret := .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  {{- if .fullName }}
  name: {{ .fullName }}
  {{- else }}
  name: "{{ $fullName }}-{{ .name | default "default" }}"
  {{- end }}
  labels: {{ $labels | nindent 4 }}
  {{- with .annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- range $key, $value := $secret.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
---
{{- end }}
{{- end }}
