{{- if .Values.services }}
{{- $fullName := include "generic.fullname" . -}}
{{- $labels := include "generic.labels" . -}}
{{- $selectorLabels := include "generic.selectorLabels" . -}}
{{- range $serviceName, $service := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  {{- if $service.fullName }}
  name: {{ $service.fullName }}
  {{- else }}
  name: "{{ $fullName }}-{{ $serviceName | default "default" }}"
  {{- end }}
  labels: {{ $labels | nindent 4 }}
  {{- with .annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ $service.type }}
  {{- if $service.externalName }}
  externalName: {{ $service.externalName }}
  {{- end }}
  ports:
    {{- range $port := $service.ports }}
    - port: {{ $port.port }}
      targetPort: {{ $port.targetPort | default $port.port }}
      {{- if $port.name }}
      name: {{ $port.name }}
      {{- end }}
    {{- end }}
  selector: {{ $selectorLabels | nindent 4 }}
---
{{- end }}
{{- end }}
