
generic:
  nameOverride: sshd

  containers:
    default:
      image:
        repository: kooldev/sshd
        pullPolicy: Always
        tag: latest
      ports:
        - containerPort: 22
      livenessProbe:
        tcpSocket:
          port: 22
      envFrom:
        - secretRef:
            name: env

  secrets:
    - name: env
      data:
        AUTHORIZED_KEYS: |
          ssh-rsa ...
          ssh-rsa ...

  services:
    default:
      type: LoadBalancer
      port: 22
      # annotations:
      #   service.beta.kubernetes.io/aws-load-balancer-type: nlb
