generic:
  nameOverride: rabbitmq
  # strategy:
  #   type: Recreate

  containers:
    default:
      image:
        repository: rabbitmq
        pullPolicy: Always
        tag: 3-management-alpine
      ports:
        - containerPort: 5672
      livenessProbe:
        tcpSocket:
          port: 5672
      envFrom:
        - secretRef:
            name: env
      # volumeMounts:
      #   - name: default
      #     mountPath: /var/lib/rabbitmq
      #     subPath: rabbitmq

  secrets:
    - name: env
      data:
        RABBITMQ_DEFAULT_USER: "user"
        RABBITMQ_DEFAULT_PASS: "pass"

  # storages:
  #   - accessModes:
  #       - ReadWriteOnce
  #     size: 1Gi

  # volumes:
  #   - persistentVolumeClaim:
  #       claimName: default

  services:
    default:
      type: ClusterIP
      port: 5672
